- id: envy
  name: envy
  description: "Envy: A CLI tool to manage your env files."
  entry: envy new
  language: go

- id: envy-pack
  name: envy-pack
  description: "Envy pack: encrypt your env files into an AES encrypted vault"
  entry: envy pack
  language: go
