- id: envy-new
  name: envy-new
  description: "Envy: A CLI tool to manage your env files."
  entry: envy new
  language: golang
  verbose: true
  pass_filenames: false

- id: envy-pack
  name: envy-pack
  description: "Envy pack: encrypt your env files into an AES encrypted vault"
  entry: envy pack
  language: golang
  verbose: true
  pass_filenames: false
